version: "3.9"
services:
  app:
    container_name: springboot_app
    image: openjdk:17-oracle
    ports:
      - 8080:8080
    volumes:
      - ./workspace:/workspace:cached
    build:
      context: ./java
      dockerfile: Dockerfile
    working_dir: /workspace
    networks:
      - br1
    tty: true

  db:
    container_name: springboot_db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - br1
    tty: true

volumes:
  db-store:

networks:
  br1:
    driver: bridge
