FROM openjdk:17-oracle

# 作業ディレクトリを設定します。
WORKDIR /workspace
RUN pwd > /tmp/pwd.txt
RUN ls -la /workspace > /tmp/test.txt
#COPY /workspace/enkai/target/enkai-0.0.1-SNAPSHOT.jar /workspace
#
#EXPOSE 8080
#CMD ["java", "-jar", "enkai-0.0.1-SNAPSHOT.jar"]
